# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [grace, Nogo]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username https://opencollective.com/smithla
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm install commander
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username mouse3687
issuehunt: # Replace with a single IssueHunt username mouse3687
otechie: # Replace with a single Otechie username mouse3687
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://mayoclinic.org/covid-19','https://netspend.com' 'https://Walmart.com']
